/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webtoonlink;

import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JLabel;

import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException;
import com.gargoylesoftware.htmlunit.WebClient;

public class Main {
    {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}

    private JFrame frame = new JFrame("WebToonLink");

    public static void main(String[] args) {
        new Main().mainMenu();
    }

    private Main() {
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    private JLabel main_label = new JLabel("<html><h1>WebToonLink</h1>Control Panel</html>");
    
    private void mainMenu() {
        frame.getContentPane().removeAll();
    }
}
